@SurveyBasket.Api_HostAddress = https://localhost:7133

GET {{SurveyBasket.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SurveyBasket.Api_HostAddress}}/api/polls

###

GET {{SurveyBasket.Api_HostAddress}}/api/polls

###
